// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCoreMicroservices.Cars.Context;

#nullable disable

namespace NetCoreMicroservices.Cars.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240513233637_carsCreate")]
    partial class carsCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NetCoreMicroservices.Cars.Domains.CarDomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("Doors")
                        .HasColumnType("int");

                    b.Property<int>("FuelId")
                        .HasColumnType("int");

                    b.Property<bool>("HasGraffiti")
                        .HasColumnType("bit");

                    b.Property<double>("MaxSpeed")
                        .HasColumnType("float");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            Doors = 0,
                            FuelId = 1,
                            HasGraffiti = false,
                            MaxSpeed = 0.0,
                            ModelId = 1,
                            Name = "Auto 1"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            Doors = 0,
                            FuelId = 2,
                            HasGraffiti = false,
                            MaxSpeed = 0.0,
                            ModelId = 1,
                            Name = "Auto 2"
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 1,
                            Doors = 0,
                            FuelId = 2,
                            HasGraffiti = false,
                            MaxSpeed = 0.0,
                            ModelId = 2,
                            Name = "Auto 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
