version: '3.4'

services:
  # netcoremicroservices.sqlserver:
  #   environment:
  #     SA_PASSWORD: "Password@1234"
  #     ACCEPT_EULA: "Y"
  #   container_name: "netcoremicroservices_sqlserver"
  #   ports:
  #     - "1433:1433"
  #   expose:
  #     - 1433
  netcoremicroservices.apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
    container_name: "netcoremicroservices.apigateway"
    ports:
      - "49630:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    # depends_on:
    #   - netcoremicroservices.sqlserver    
 
  netcoremicroservices.auth:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - SQL_SERVER_HOST=netcoremicroservices.sqlserver
      - SQL_SERVER_PORT=1433
    container_name: "netcoremicroservices.auth"
    ports:
      - "49631:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    # depends_on:
    #   - netcoremicroservices.sqlserver
  netcoremicroservices.cars:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - SQL_SERVER_HOST=netcoremicroservices.sqlserver
      - SQL_SERVER_PORT=1433
    container_name: "netcoremicroservices.cars"
    ports:
      - "49632:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    # depends_on:
    #   - netcoremicroservices.sqlserver      

  netcoremicroservices.users:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - SQL_SERVER_HOST=netcoremicroservices.sqlserver
      - SQL_SERVER_PORT=1433
    container_name: "netcoremicroservices.users"
    ports:
      - "49633:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    # depends_on:
    #   - netcoremicroservices.sqlserver

 
