#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app


FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["netcoremicroservices.users/NetCoreMicroservices.Users.csproj", "netcoremicroservices.users/"]
COPY ["netcoremicroservices.commons/NetCoreMicroservices.Commons.csproj", "netcoremicroservices.commons/"]
RUN dotnet restore "./netcoremicroservices.users/NetCoreMicroservices.Users.csproj"
COPY . .
WORKDIR "/src/netcoremicroservices.users"
RUN dotnet build "./NetCoreMicroservices.Users.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./NetCoreMicroservices.Users.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "NetCoreMicroservices.Users.dll"]